name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if previous artifact exists
      id: artifact-check
      run: echo "Checking for previous artifact"
      continue-on-error: true

    - name: Restore database if exists
      if: steps.artifact-check.outcome == 'success'
      uses: actions/download-artifact@v2
      with:
        name: discord_bot_db
        path: discord_bot.db

    - name: Run the bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: python main.py

    - name: Save database
      if: always()  # This ensures the step runs even if previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: discord_bot_db
        path: discord_bot.db
